HomeWork (2022-04-27) - Создание API. Swagger-UI, Postman
Lancoid/sky-pro-education-spring-rest pull request #1
Opened 2022-04-27 13:49 UTC by Lancoid

Выполнил домашнее задание по теме "Создание API. Swagger-UI, Postman"

2022-04-27 19:09 UTC, OlgaLugacheva requested changes

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    @PostMapping("{color}")
здесь должен быть Get - маппинг

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
> +    @PostMapping("{age}")
здесь должен быть Get- маппинг и age должно быть параметром запроса

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/model/Faculty.java
> +    private final Long id = null;
не должен быть null

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/model/Student.java
> +    private final Long id = null;
почему null ?

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public ResponseEntity<List<Faculty>> getByColor(@PathVariable String color) {
color Должен быть параметром запроса @RequestParam

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/service/faculty/FacultyServiceImpl.java
> +        generatedFacultyId++;
где-то здесь нужно присвоить через setId новый id

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/service/faculty/FacultyServiceImpl.java
> +        facultyMap.put(generatedFacultyId, faculty);
здесь ключом может быть сам id у Faculty

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/service/faculty/FacultyServiceImpl.java
> +        facultyMap.put(facultyId, faculty);
прежде, чем обновлять и складывать сущность в карту, сначала нужно проверить, а есть ли она там - contains

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/service/student/StudentServiceImpl.java
> +
смотри комментарии для FaculryServiceImpl - здесь все то же самое

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/model/Faculty.java
> +    private final String color;
где геттеры и сеттеры? 
equals, toString, hashCode?

2022-04-27 19:09 UTC, OlgaLugacheva commented on src/main/java/ru/hogwarts/school/model/Student.java
> +    }
где геттеры и сеттеры? 
equals, toString, hashCode?

2022-04-28 15:17 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public ResponseEntity<List<Faculty>> getByColor(@PathVariable String color) {
Исправлено

2022-04-28 15:17 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    @PostMapping("{color}")
Исправлено

2022-04-28 15:17 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
> +    @PostMapping("{age}")
Исправлено

2022-04-28 15:19 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/model/Faculty.java
> +    private final Long id = null;
Исправлено

2022-04-28 15:20 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/model/Student.java
> +    private final Long id = null;
Исправлено

2022-04-28 15:21 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/service/faculty/FacultyServiceImpl.java
> +        generatedFacultyId++;
Исправлено

2022-04-28 15:21 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/service/faculty/FacultyServiceImpl.java
> +        facultyMap.put(generatedFacultyId, faculty);
Исправлено

2022-04-28 17:04 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/service/faculty/FacultyServiceImpl.java
> +        facultyMap.put(facultyId, faculty);
Исправлено

2022-04-28 17:05 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/service/student/StudentServiceImpl.java
> +
Исправлено

2022-04-28 17:05 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/model/Faculty.java
> +    private final String color;
Исправлено, завёл через lombok

2022-04-28 17:05 UTC, Lancoid commented on src/main/java/ru/hogwarts/school/model/Student.java
> +    }
Исправлено, завёл через lombok

2022-04-28 18:07 UTC, OlgaLugacheva approved these changes

2022-04-28 19:09 UTC, merged